### ISSUE TITLE
Create links on Unix/Linux

### ISSUE THREAD

**Issue by abonhote** [DmitriiShamrikov/mslinks#15]
Hi!

While your code works brilliantly on Windows, it would be awesome to get this running on Linux. I've seen plenty of checks and input modifications in ShellLink.java, they're all doomed to fail or raise NPEs in a Linux environment.

Any idea on how to achieve this? You'd somehow offer a way to override all checks and just trust the dev that what he/she puts in is really valid.

Cheers

André

PS: Reason behind: I'd like to create 100s of links out of an oracle database.

**Comment by BlackOverlord666** [comment]
Hi! I did some research and unfortunately I couldn't find a way to do this on Linux. The point is link files store absolute paths mostly but on Linux it is not possible to get windows absolute path with drive letter. 
However, you may notice that if you move lnk file and/or it's target file in windows explorer, it somehow still valid. I have no idea how this magic works, but I can say for sure that setting relative path field is not enough to make it working.

If you want some more technical details there is a core structure LinkTargetIDList which is responsible for getting location of target file, but due to lack of documentation most of the work done by reverse ingeneering. I guess it stores some low-level filesystem marks for each component of the path which helps windows explorer to find correct target even in case of moving.

I will appreciate PR if you willing to dig into that stuff.

**Comment by abonhote** [comment]
Hi! Thanks for your quick response - and sorry for my late one. Apparently lnk files can be created on Linux, see here [1]. In your code, you're doing plenty of checking (which is great when running on Windows), but actually most of that is not required. Given the user, err, developer knows what he/she's doing, you could simply take what's being offered and create the link, regardless of the validity of the parameters. It's up to the dev to make sure that the values are correct.

We've got plenty of windows clients here with very similar setups. For example, in subdirectories of D:\xyz, we have links to all our databases, putty shorts and stuff. The origin of these files is a linux machine which moves files around in a very complicated way (based on the database, which keeps the repository) and publishes them to subversion. The clients then just run svn update. I would like to skip the complicated part and create new links from scratch.

If you're willing to add an option to skip all checks, that would already do the job, I think 😉 Maybe I find the time to work on it one day, I'll create a PR then.

Cheers

André

[1] [http://www.mamachine.org/mslink/index.en.html](http://www.mamachine.org/mslink/index.en.html)

**Comment by BlackOverlord666** [comment]
Well, in your case i recommend you to look at SheILink.setTarget function and set LinkTargetIDList manually

**Comment by ademeglio** [comment]
@vatbub , I wouldn't merge in the above code directly. You could create new methods that uses the above though to something like createLinkWhileInLinuxEnvironment(String target, String linkSource). I think you would only have to get rid of the paths.

**Comment by vatbub** [comment]
It's very easy to distinguish between Linux and Windows using Apache's commons-lang library and thus shouldn't be too hard to merge the above code in. I'll have a look at it in the upcoming days

**Comment by ademeglio** [comment]
Cool, I look forward to seeing it and learning something new.

**Comment by DmitriiShamrikov** [comment]
Thank you, @ademeglio 
I'll take a look at the end of the week

**Comment by jredfox** [comment]
I refuse to use a library that only works on windows

**Comment by DmitriiShamrikov** [comment]
I added ShellLinkHelper in version `1.0.7` with more options to control how a link should be created. In particular, there is an Options parameter in `setNetworkTarget` and `setLocalTarget` functions which can force file or directory type on the target in case when it's not possible to check it in runtime.
