### ISSUE TITLE
Character Encoding Incorrect

### ISSUE THREAD

**Issue by battlesteed** [DmitriiShamrikov/mslinks#30]
here is my .lnk file,one is japanese,another is chinese 
![QQ截图20210815145555](https://user-images.githubusercontent.com/6690928/129469905-fdb561d0-2d49-4361-97d1-b9d502769eb8.png)

here is my code
`ShellLink shellLink  = new ShellLink(file);
System.out.println(shellLink.getLinkInfo().getLocalBasePath());`
and console out put:
`O:\game\J�c����B\Start.exe
A:\�½��ı��ĵ�.txt`
![output](https://user-images.githubusercontent.com/6690928/129469984-8710b289-450c-4b71-a8c4-1f5b52b5505c.png)

my os is windows10 x64  Chinese version.

here is the sample .lnk files.
[lnk.zip](https://github.com/DmitriiShamrikov/mslinks/files/6987475/lnk.zip)

when I change your code
`localBasePath = data.readString(pos + size - data.getPosition());`
to
`localBasePath = new String(bytes,"GBK");`
the "新建文本文档" file can be correct printlned on console,but another file is incorrect. I change Charset to 'Shift_JIS' the other "JＤ温泉。" file can be correct printlned.

is there a way to read the .lnk file's Charset ?

**Comment by tresf** [comment]
Hi,

On Windows:
* Do NOT use Command Prompt / `cmd.exe`
* Write a UTF-8 log file using Java
* Compiling your application using `-encoding UTF8`.
* Set up file logger to use UTF-8 too.

See example below: (I can NOT get this to work using CMD)
```java
public class Main {
    public static void main(String[] args) {
	    System.out.println("こんにちは");
    }
}
```

Try to compile WITHOUT encoding:
```cmd
javac.exe Main.java
```

```diff
- Main.java:3: error: unmappable character (0x81) for encoding windows-1252
-        System.out.println("�?�ん�?��?��?�");
```
(above error is for Cp1252, sorry, but very similar error should occur on other similar unmappable characters for `Shift_JIS`, `GBK`, etc).

This is because Java will use default encoding to **COMPILE**.  It needs to be compiled using UTF-8. 😠 

```diff
- javac.exe Main.java
+ javac.exe -encoding UTF-8 Main.java
```

Ok, it is good!  But this will not work very well with Command Prompt / `cmd.exe` (at least not on my computer) because Command Prompt is very bad at displaying certain characters. 😠 😠 

This does NOT work on my computer:
```cmd
C:\> chcp 65001
Active code page: 65001
```

(I also installed [Japanese language pack](https://user-images.githubusercontent.com/6345473/129593187-743b9a2a-d734-4f1e-947a-501bed745687.png), change Terminal font and did NOT have success)

```java
public class Main {
    public static void main(String[] args) {
	    System.out.println("テスト");
    }
}
```

```cmd
javac.exe -encoding UTF-8 Main.java
```

```cmd
java -D"java.encoding=UTF8" Main
```

Shows this:
> ![image](https://user-images.githubusercontent.com/6345473/129597026-76d32a93-522a-4e43-b70f-3d3cc6ac3547.png)

.. but copy/paste to Chrome shows UTF-8.  This is better. :)

The question marks are generally a problem between Microsoft + Java , not MSLinks.  This is because Java is outputting a different encoding than what CMD is expecting.

Instead, tell Java to write a UTF-8 log file and compile using UTF-8.

```java
import java.io.*;
import java.nio.charset.*;

public class Main {
    public static void main(String[] args) throws Exception {
        String utf8File = System.getProperty("user.home") + "/Desktop/utf8.txt";
        OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(utf8File), StandardCharsets.UTF_8);
        writer.write("こんにちは");
        writer.close();
    }
}
```

```cmd
javac.exe -encoding UTF-8 Main.java
java Main
```

Notepad looks good!

<img src="https://user-images.githubusercontent.com/6345473/129598246-1f12dfe9-f3e9-44d3-8891-d1b2cf162559.png" width="300px"/>



> is there a way to read the .lnk file's Charset

Not easily.  IBM maintains a comprehensive IC4UJ which can help with encoding, but this tool can be very difficult to use.  In most cases it's easier to just know/force which encoding Java is using.

This problem is complex because many characters sets used historically are extensions of others, meaning some characters will print fine, others will print incorrectly.  UTF-8 is supposed to fix this problem, but for historical purposes Java and Windows like to use old encodings instead by default.

I have installed Japanese as default language in Windows, this still does not work.

**However**, I test same code on MacOS, no problem. :(

This problem is very widespread and many people are confused about this:

https://stackoverflow.com/a/57134096
https://stackoverflow.com/q/3780378
https://stackoverflow.com/q/35141175
https://stackoverflow.com/q/10890578
https://social.technet.microsoft.com/Forums/windowsserver/en-US/728d6169-07fa-4e93-8a41-f9fa6dd8d9d9/displaying-japanese-in-english-command-prompt?forum=w7itprogeneral

Please try to not use Command Prompt and write to UTF-8 file.  😅

**Comment by battlesteed** [comment]
> ```java
>   OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(utf8File), StandardCharsets.UTF_8);
>         writer.write("こんにちは");
>         writer.close();
> ```
thanks for your help.
I always compiled using UTF-8 to do my java job, and I try to write a UTF-8 log file,but it is the same as the console output. 😅

**I think the reason is the two .lnk files have different charset ,mslinks use wrong charset to parse it .**

because when I modify the LinkInfo.java file line 58
`localBasePath = data.readString(pos + size - data.getPosition());`
to
`localBasePath = new String(bytes,"GBK");`
the "新建文本文档" file can be correct printed on console,but another file is incorrect.like this:
![GBK_Output](https://user-images.githubusercontent.com/6690928/129735599-1e2f90b7-c547-4ff3-a970-8f5d1cc4b1e0.png)

when I modify to
`localBasePath = new String(bytes,"Shift_JIS");`
 the other "JＤ温泉。" file can be correct printed,but another file is incorrect.like this:
![Shift_JIS_Output](https://user-images.githubusercontent.com/6690928/129735694-eac8001f-f3f6-4179-8e61-90562a2ebec2.png)
 when I modify to
`localBasePath = new String(bytes,"UTF-8");`
the two files be printed incorrect.like this:
![UTF-8_Output](https://user-images.githubusercontent.com/6690928/129736367-8e04e983-75f3-4cd9-8ed2-51e7f170a253.png)

so I think the way to deal this problem is find out .lnks file`s Charset, and use the Charset to prase it on LinkInfo.java file line 58.

but ~~because  my english is not very good~~ I can not find the way to read the .lnk file's Charset from [Shell Link (.LNK) Binary File Format](http://msdn.microsoft.com/en-us/library/dd871305.aspx).

**Comment by tresf** [comment]
@battlesteed you are right, the encoding differs... 

Please see this code comment:
https://github.com/DmitriiShamrikov/mslinks/blob/ba172b89ff4d419e880235ddc68a26f737b292ee/src/mslinks/data/ItemID.java#L267-L268

This explains why ASCII variants are needed to read these lines.

Other examples use the `defaultCharset`, which I believe should have an override to force UTF-8 (or default to UTF-8 with the option to force `defaultCharset` in special circumstances.

https://github.com/DmitriiShamrikov/mslinks/search?q=Charset:

https://github.com/DmitriiShamrikov/mslinks/blob/ba172b89ff4d419e880235ddc68a26f737b292ee/src/mslinks/data/CNRLink.java#L128

https://github.com/DmitriiShamrikov/mslinks/blob/ba172b89ff4d419e880235ddc68a26f737b292ee/src/mslinks/data/VolumeID.java#L90

https://github.com/DmitriiShamrikov/mslinks/blob/79751506cc95d50385ec1265f0083368ac047245/src/mslinks/LinkInfo.java#L81

This seems to suggest the following:

* `defaultCharset` will be used most of the time, which will differ between systems. 
* There is a field reserved for DOS names that will use "ASCII".  I would not expect you to use this field, e.g. `C:\PROGRAM~1`, etc.

You may write code to detect encoding, but I believe it will be a trial and error effort and will not be 100%.  Many encodings do not error when the wrong one is chosen. 😞

I believe MSLinks should be recompiled with UTF-8 enabled 100% of the time.

**Comment by tresf** [comment]
Also, the ICU4J class which tries to offer detection:

https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/text/CharsetDetector.html

**Comment by DmitriiShamrikov** [comment]
Hello, thank you for your interest in mslinks!

Unfortunately, there is no information about charset stored in the .lnk files. In most cases there are two versions of a string: the first one is stored in default (system) code page, the second is in unicode which is essentially UTF-16. 

I can guess that running java with forced default encoding as UTF-8 might actually be the problem. In this case it will try to decode strings which were stored in your default code page as UTF-8 . 
You can test it by running: `System.out.println(Charset.defaultCharset().name());`

Sometimes when the string can be encoded with the default code page, the unicode version is not stored at all! So I belive that changing your OS locale can break some things too.

@tresf I don't think **compiling** with any forced encodig will change anything, because it is applied to **source files** and they don't contain anything other that normal ASCII symbols.

**Comment by tresf** [comment]
> @tresf I don't think compiling with any forced encodig will change anything, because it is applied to source files and they don't contain anything other that normal ASCII symbols.

You're right, it only needed due to isolated unit tests requiring it and won't affect projects in any similar fashion to the bug report.

**Comment by battlesteed** [comment]
> You can test it by running: System.out.println(Charset.defaultCharset().name());
thanks for your help.I tryed and it print "UTF-8"

I think there maybe a way to parse two different charset .lnk file at the same time.because windows can do this,like the picture
![parse_right](https://user-images.githubusercontent.com/6690928/129841527-472b9825-12c3-450f-bfd7-abb1d8a85636.png)
but I don`t know how windows can do it. I guess windows do it by detect encoding.the reason is:

I use hex editor modify  JＤ温泉。.lnk file's localBasePath "O:\game\JＤ温泉。\Start.exe" charset from Shift_JIS to GBK, like this:
![modif](https://user-images.githubusercontent.com/6690928/129842485-bef248df-eaef-4279-adc5-a4d27c5f79a1.png)
left is Shift_JIS ,right is GBK
after modifed, windows still parse it correct.if windows parse .lnk file dependent on the information about .lnk file`s charset ,then  windows should parse it incorrect.so I think windows parse .lnk by detect encoding,and I will try the same way.

@tresf  I will try ICU4J ,thank you.

**Comment by tresf** [comment]
I believe that Windows tries to decode using UTF-8 and then falls back to the system ANSI charset (or perhaps it does the same, but in reverse).  A crude mockup could (for example) check the second character for a colon.

An article which helps explain this is here (Chinese (Simplified), requires translation) http://blog.sina.com.cn/s/blog_53c1950a010158mw.html

The article does have a code snippet to help detect encoding, but I believe it still relies on two values, `CP_ACP` and `CP_OEMCP` in Windows.

These values are referenced by APIs such as [`MultiByteToWideChar`](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar) and [`WideCharToMultiByte`](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte).  If you can get them to work, [JNA](https://github.com/java-native-access/jna) can expose C++ APIs to Java for you.

**Comment by DmitriiShamrikov** [comment]
@battlesteed LocalBaseBath string is not the one that is displaying in link properties window. LinkTargetIDList is the most important structure and the one that is used to reconstruct the path if present. It starts from 4E position on your screenshot and contains each part of the path is separate field. Yes, there a lot of duplicated info in .lnk files.

**Comment by battlesteed** [comment]
thanks for your help. I tryed ICU4J,but in most cases it detect a wrong encoding.so finally I use this code to detect encoding:
`new File(localBasePath).exists()`
if not exists,I will try next charset until exists.
